### ISSUE TITLE
Bar graph panel expanding issue when boxes are unchecked

### ISSUE THREAD

**Issue by alynne-phet** [phetsims/capacitor-lab-basics#106]
@arouinfar @jessegreenberg I was running the simulation on Mac Safari and noticed that when you click the check boxes to show the capacitance, plate charge, and stored energy values the box expands as the values get larger. When you unclick the boxes to no longer show the values, the box still expands. Is this an issue or is this ok with you?

https://drive.google.com/file/d/0B2k01kdMqJLDbEpNVkJBSWVGbEE/view?usp=sharing

**Comment by jessegreenberg** [comment]
Good catch @alynne-phet, definitely a bug.  It is happening because the 'Plate Charge' graph extends beyond the bounds of the panel, and was introduced because of https://github.com/phetsims/capacitor-lab-basics/issues/107.

Fixing https://github.com/phetsims/capacitor-lab-basics/issues/107 should fix this issue as well.

**Comment by arouinfar** [comment]
Nice work @alynne-phet. Looks like @jessegreenberg has diagnosed the problem, so I'll go ahead and reassign to @andrewadare.

**Comment by andrewadare** [comment]
Looks like 2da19eeeab039155b555af170181cf1167c716ed fixed this one for free.
