### ISSUE TITLE
Voltmeter text rendering with ?stringTest=double

### ISSUE THREAD

**Issue by alynne-phet** [phetsims/capacitor-lab-basics#118]
From https://github.com/phetsims/scenery/issues/469#issuecomment-225923568

@jessegreenberg I see this in CLB 1.0.0-dev.22 with `?stringTest=double` and OS X 10.11.5 Safari. The voltmeter text exhibits this issue when it is initially taken out of the box. This issue seems to fix itself once you take a voltage measurement. 

For phetsims/tasks/issues/615

Screenshots:
![image](https://cloud.githubusercontent.com/assets/19288972/16049148/e1456bb8-3213-11e6-9d04-de14a72a4cb8.png)

![image](https://cloud.githubusercontent.com/assets/19288972/16049152/e5208434-3213-11e6-99f0-1a3324473952.png)

**Comment by andrewadare** [comment]
Also see #61

**Comment by jessegreenberg** [comment]
Thanks for bringing this up @alynne-phet and referencing https://github.com/phetsims/scenery/issues/469#issuecomment-225923568, we didn't used to see this in built versions.  Closing this issue since it is likely an issue with '+' concatenation in the sringTest tools for most sims in Safari.  Progress will be tracked there in the scenery issue above.
