### ISSUE TITLE
createBulb doesn't look right

### ISSUE THREAD

**Issue by andrewadare** [phetsims/capacitor-lab-basics#129]
@jessegreenberg, while trying to instrument BulbNode, I came across this code in CLBLightBulbScreen:
```js
var iconNode = new BulbNode.createBulb();
```
Shouldn't this be named createBulbNode(), and call `new BulbNode` somewhere from within, instead of here at the call site? Again, I'm new to the factory pattern, so maybe I am missing something.

And in BulbNode,
```js
/** Factory function to create a BulbNode.  This creates a node that is not linked to any model properties.
     * This is useful in cases such as control panel content where the node should not respond to model changes.
     *
     * @param {Object} options
     */
    createBulb: function( options ) {
      return createBulb( options );
    }
```
This looks confusing, but for different reasons than those reported by @pixelzoom in #123. Why is this indirection necessary?

**Comment by pixelzoom** [comment]
`BuldNode.createBulb` is also confusing because (at first glance) it appears to call itself, when in fact it calls a private function that has the same name.

The indirection is apparently necessary because both the BulbNode constructor and `BulbNode.createBulb` call the private function `createBulb`.

If the purpose of this is to provide a bulb icon that has no associated model element, then you might consider renaming to the static function to `createIcon`, and the private function to something else.

**Comment by jessegreenberg** [comment]
This was very confusing.  I renamed the static function to ```createBulbIcon``` and the private function to ```drawBulbNode```.  I also moved the private function below the BulbNode constructor because I think we agreed that the constructor should be near the top of the file.  @andrewadare would you mind reviewing again?

**Comment by andrewadare** [comment]
@jessegreenberg things look much clearer after 0d37061! Thanks.
