### ISSUE TITLE
Closed vs Open circuit representations

### ISSUE THREAD

**Issue by phet-steele** [phetsims/capacitor-lab-basics#140]
There was a discussion between myself and others about the behaviour of dragging the switch and when the circuit is open vs. closed. The sim doesn't consider a circuit closed if the switch is still being dragged, and only makes the circuit closed once the switch is released from the user's control. However, there is absolutely no visual difference between an open or closed circuit. For example, here is a screen shot of me dragging the switch into place. It looks like the circuit *should* be closed, but it is not and causes this very unphysical looking situation (the plate should be discharged/discharging):
![img_0066 1](https://cloud.githubusercontent.com/assets/5863899/19093775/cf6a2ac6-8a49-11e6-93fa-3bca844f0132.PNG)

To avoid any confusion with this, I suggested to @arouinfar that we adopt the way CCKBBS handles circuits (she generally agreed). Any disconnected, open wire vertices have a red outline. Once the circuit is closed, the connected vertices become black and soldered together with a gray dot. 

<img width="478" alt="screen shot 2016-10-04 at 3 32 19 pm" src="https://cloud.githubusercontent.com/assets/5863899/19093300/ce1b1e5c-8a47-11e6-963d-ac39a68a29c2.png">

This would work nicely in CLB, too. See below for the beautiful Google Drawing mockup (I'm sure @arouinfar could make a more accurate one, nudge nudge). The "pin" or round ball at the end of the switch will behave like the solder, where it would **only** appear once the switch is released and the circuit becomes closed. I'd think the behaviour of the middle position would ideally always show as open (no black circle or "pin" when releasing the switch in the middle). EDIT: @arouinfar had a better suggestion for the middle position below.
![untitled drawing 1](https://cloud.githubusercontent.com/assets/5863899/19092376/976472c2-8a43-11e6-8f26-49750622ffd4.png)

@arouinfar anything you would like to change or add? I'm sure I missed something!

For phetsims/tasks/issues/706.

**Comment by arouinfar** [comment]
@phet-steele I think this an excellent solution to the problem you've identified. I think your Google drawings look great; probably better than I could do in the same program. I do not have any functional changes to request.

@andrewadare can you please make this change? I can do a fancier mockup in Illustrator if you'd like, but I think @phet-steele's mockup captures the interaction.

**Comment by arouinfar** [comment]
One situation that isn't reflected in @phet-steele's mockups is what happens when switch in the released in the middle position.

In the middle position, it doesn't make sense for a solder joint to appear, but the dashed line should turn black, since the switch is "connected" to one of the positions.

![image](https://cloud.githubusercontent.com/assets/8419308/19126642/fbba6866-8af8-11e6-912c-234abc01e1ae.png)

**Comment by andrewadare** [comment]
To summarize the design revision:
* Make the switch-end (the shaded ball) invisible while the switch is in transit; replace with red dashed circle
* Make the red dashed circle on the switch turn black when a connection is made. Make the shaded sphere reappear inside it. 
* In order to match these drawings, the dashed circles may need to be enlarged to surround the shaded sphere.
* None of the event handling logic needs to change at all; the proposal is to only modify how things appear in the different switch states.

**Comment by arouinfar** [comment]
👍 @andrewadare

**Comment by andrewadare** [comment]
I think this is now implemented as specified:

![image](https://cloud.githubusercontent.com/assets/154163/19279224/cc3bef2a-8f9d-11e6-9770-88d1c7e66769.png)

![image](https://cloud.githubusercontent.com/assets/154163/19279247/e5aeae02-8f9d-11e6-80f8-69dda6f45fd6.png)

![image](https://cloud.githubusercontent.com/assets/154163/19279275/fc70af5a-8f9d-11e6-879d-ff757c67ead3.png)

**Comment by arouinfar** [comment]
@andrewadare looks good, but I have a few tweaks to request

* Increase the diameter of the dashed lines so that it doesn't overlap the solder blob.
* Shorten the wire so that it only extends half-way into the vertex.

![image](https://cloud.githubusercontent.com/assets/8419308/19281145/0e5e4260-8fa6-11e6-971c-ef9a0de0db7b.png)

**Comment by andrewadare** [comment]
It turns out that making the switch wire shorter is not so easy. There is no explicit length parameter for wire segments; instead they are constructed as follows:

SwitchNode.wireSwitchNode uses CircuitSwitch.switchWire, which uses CircuitSwitch.switchSegment, which uses CircuitSwitch.activeConnection, which is an object that contains (among other things) an (x,y,z) position of the switch contact.

Somehow the length would need to be constructed from the difference of the endpoints. @jessegreenberg, since you are the author of this code, do you have any recommendations on how to go about this? The two strategies I explored were to (a) make a surrogate switch in the model that has different geometry, or (b) modify the wireSwitchNode after creating it from the model. In either case, the implementation looks messy, and I don't see a simple solution.

**Comment by andrewadare** [comment]
![image](https://cloud.githubusercontent.com/assets/154163/19324888/ed9ad206-9080-11e6-8a3b-d39c9e0976e6.png)
![image](https://cloud.githubusercontent.com/assets/154163/19324914/0bd5409e-9081-11e6-9923-828e079a5d34.png)
![image](https://cloud.githubusercontent.com/assets/154163/19324935/189c85d0-9081-11e6-8f7d-b63ffac80887.png)
![image](https://cloud.githubusercontent.com/assets/154163/19324999/63c4c6d0-9081-11e6-92f6-f283a9fad2ae.png)

Thanks to @jessegreenberg, this change is hopefully complete now.

**Comment by arouinfar** [comment]
The version @andrewadare showed in status looks good. There are some minor differences from the mockup, but I don't think any cosmetic changes need to be made. Leaving it to @phet-steele and team to test the functionality in dev.29.

**Comment by jessegreenberg** [comment]
This looks great! :) Another benefit of this is that the shading on the solder blob is always correct when visible.  Before, the shading would rotate with the blob which looked a bit strange.

**Comment by phet-steele** [comment]
The points in this issue have been addressed and are working well, thanks to everyone for this change.
