### ISSUE TITLE
Checking for intersection of shape with bounds is not precise

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/capacitor-lab-basics#143]
@phet-steele just found this issue and described it to me.  To determine whether probe tips are touching, ```probesAreTouching``` determines if the *shape* of the positive probe tip intersects with the *bounds* of the negative probe tip

```js
      return this.shapeCreator.getPositiveProbeTipShape().intersectsBounds( this.shapeCreator.getNegativeProbeTipShape().bounds );
```

This can create situations like the following:
![snap1](https://cloud.githubusercontent.com/assets/6396244/19365921/34731090-9152-11e6-9daf-afa0a98112d3.PNG)

And perhaps more importantly:
![snap2](https://cloud.githubusercontent.com/assets/6396244/19365928/39fab5ae-9152-11e6-8c9f-b2e8b5846cfa.PNG)

I think the reason for this is that it is not possible to check for the intersection of two arbitrary shapes, but maybe there is a work around.

I am not sure if this issue is an important issue.  Assigning to @andrewadare and @arouinfar for thoughts.

**Comment by andrewadare** [comment]
@jessegreenberg, is it possible to check for intersection a rotated rectangle? I'm not familiar enough with Scenery to know. If so, we can use skinny rectangles rotated 45 degrees.

**Comment by jessegreenberg** [comment]
I could be wrong, but I don't think so.  A scenery rectangle uses shape, and a dot rectangle uses bounds which are always axis aligned, even when transformed.

**Comment by jessegreenberg** [comment]
Over skype, one recommendation was ```Shape.interiorIntersectsLineSegment``` to check when line segments of one rectangle intersect the shape of the other.  Documentation of that function suggests that the segment needs to be fully contained by the shape to be considered an intersection, so I am not sure if this will work.

I am also wondering if it would work to rotate each rectangle by ```CLBModelViewTransform.yaw``` in ```Voltmeter.probesAreTouching``` and then use something like ```rect1.bounds.intersectsBounds( rect2.bounds )``` since the rectangles are now axis aligned.

**Comment by arouinfar** [comment]
@jessegreenberg I've never seen students use the probes so closely together. However, I think the situation in your 2nd screenshot is problematic, so I think it's worth continuing to investigate a fix.

**Comment by andrewadare** [comment]
@jessegreenberg I explored your ideas mentioned above, but was unable to see any difference compared to un-rotated bounds-to-bounds intersection testing.

Since Scenery doesn't have what we really want (namely something like a `Shape.intersects(shape)` function, I decided to iterate over every point in one of the shapes and check for containment within the other:

```js
    probesAreTouching: function() {
      var touching = false;
      var posShape = this.shapeCreator.getPositiveProbeTipShape();
      var negShape = this.shapeCreator.getNegativeProbeTipShape();
      posShape.subpaths.forEach( function( subpath ) {
        subpath.points.forEach( function( point ) {
          if ( negShape.containsPoint( point ) ) {
            touching = true;
            return;
          }
        } );
        if ( touching ) { return; } // For efficiency
      } );
      return touching;
    },
```
Despite the looping, in my limited tests I didn't notice any performance issues.

**Comment by andrewadare** [comment]
The function above would not be very efficient for arbitrary Shapes, but here it is only being applied to simple rectangles.

**Comment by phet-steele** [comment]
From https://github.com/phetsims/capacitor-lab-basics/issues/143#issuecomment-253863686:
> I've never seen students use the probes so closely together.

Agreed, and with the recent improvements, students would have to get them even closer. This is not an issue:

![screen shot 2016-10-26 at 10 37 24 am](https://cloud.githubusercontent.com/assets/5863899/19735295/38b1d73e-9b68-11e6-99c9-a2bbf31e27ef.png)


> the situation in your 2nd screenshot is problematic

In order to show 0V across charged plates, one would now have to be very precise and do it deliberately. I doubt the following, extreme case, would happen accidentally. I might be exaggerating, but moving either probe even a single pixel in either direction would show the correct V:
![screen shot 2016-10-26 at 10 43 02 am](https://cloud.githubusercontent.com/assets/5863899/19735494/14becfc0-9b69-11e6-9822-cc8d73786b33.png)

@arouinfar, you may comment on how problematic the above screenshots might be (or the new english word: the "problemicity"). When compared to the screenshots in the original comment, my vote is that these have much less problemicity. Furthermore, taking into account the technical limitations of solving this problem any further, I am satisfied with the current state of 1.0.0-dev.32. @arouinfar, close at your discretion.

From https://github.com/phetsims/capacitor-lab-basics/issues/143#issuecomment-255839705:


> Despite the looping, in my limited tests I didn't notice any performance issues.

Nor did I. macOS browsers and an iPad2 didn't show any problems.

**Comment by arouinfar** [comment]
I agree @phet-steele. I find that the updated screenshots exhibit less problemicity. Closing.
