### ISSUE TITLE
Explore wider plate separation range

### ISSUE THREAD

**Issue by andrewadare** [phetsims/capacitor-lab-basics#151]
To better observe the inverse relationship between charge Q and plate separation d, it may help to change from the existing d = 5-10mm range to 2-10mm.

**Comment by andrewadare** [comment]
![image](https://cloud.githubusercontent.com/assets/154163/19936420/f00a21c8-a0e2-11e6-9ce3-8fa781d05b9d.png)

A screenshot from the PhET-iO Lab Book wrapper:
![image](https://cloud.githubusercontent.com/assets/154163/19936449/07897d3a-a0e3-11e6-9258-bb5d77bf333a.png)

Empirically, with only 5-10mm to go on, it's tempting for students to infer a negative linear Q vs d relationship instead of the correct 1/d dependence. Over the 2-10mm, it's much clearer.

**Comment by andrewadare** [comment]
A dev version is up here:

http://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.0.0-dev.33/capacitor-lab-basics_en.html

Note that this is an excursion from the "official" testing cycle that's currently tracked in https://github.com/phetsims/tasks/issues/716.

I'm noticing that the bars in the horizontal chart are now maxing out well inside the new physical ranges, so they'll need adjustment.

**Comment by arouinfar** [comment]
@andrewadare I think that reducing the separation to 2mm definitely adds some flexibility to the sim's use. I think we originally made the minimum 5mm due to the scaling of the graph, and perhaps because the electric field lines can be somewhat hard to see when the plates are so close. I think we've overcome the first of these concerns (though some tweaking will be necessary). After seeing the latest dev, I think the electric field lines are still reasonably visible at 2mm. Plus, students can always adjust the plate separation to see that the the E-field lines are always orthogonal to the plates.

We will need to address the scaling of the bar graph, though. I think that the max bar length should correspond to 2.7x10^-12 so that all three bars are on-scale while connected to the battery.
<img width="573" alt="screen shot 2016-11-02 at 11 28 18 am" src="https://cloud.githubusercontent.com/assets/8419308/19939643/7eb4d1fa-a0ef-11e6-9169-87d069e13532.png">

**Comment by ariel-phet** [comment]
I played around with this version for awhile, and the scaling for the bar graph seemed to be the only issue, but that seems to be fairly outweighed by the increased range of exploration

**Comment by arouinfar** [comment]
Discussed during the 11/3/16 design meeting

We like the 2mm separation, but @andrewadare should make a few more tweaks.
- [ ] Rescale bar graphs so that the max value is 2.7 p[unit] for all three bars.
- [ ]  Reduce E-field line stroke weight to 1 pixel
- [ ] Reduce E-field arrowhead size to -- what @andrewadare demoed looked good

Reducing the E-field stroke and arrowhead size will make the field look a bit less like a solid block at high voltages.

**Comment by andrewadare** [comment]
It was also requested in yesterday's meeting to snap the plate area and separation drags to rounder values. The plate separation was easy; drags now snap to increments of 0.2 mm, and every value in the 2-10mm range can be visited. The plate area is a little more complicated.

In PlateAreaDragHandler, I modified the drag callback as follows:
```js
drag: function( event ) {
  var pMouse = event.pointer.point;
  var plateWidth = self.getPlateWidth( pMouse );

  // Discretize the plate area to round values by scaling m -> mm, rounding, then scaling back.
  // Plate area drags should then snap only to round integer values (in mm^2).
  var plateArea = Util.roundSymmetric( 1e6 * plateWidth*plateWidth ) / 1e6;
  capacitor.setPlateWidth( Math.sqrt( plateArea ) );
}
```
The drag resolution is limited by `event.pointer.point`, which is in discrete pixels. There are not enough pixels in the drag interval to cover every integer value in the plate area range 100-400 mm^2. So the code above addresses the request in that only integer plate areas are shown, but you still can't visit every single integer-valued area through the drag.

**Comment by andrewadare** [comment]
Significant refactoring was required (see 918168e, c0907dd, 9b6ab50, and 	14d6162), but the bar meter ranges are now individually settable in a much more flexible way. I found the range max values as described [here](https://github.com/phetsims/capacitor-lab-basics/blob/14d6162058c23ff4d08845b307b08938ca7a0a7e/js/common/CLBConstants.js#L105-L113). I think this achieves what we're going for.

**Comment by andrewadare** [comment]
@arouinfar - I have a question about this:
> Rescale bar graphs so that the max value is 2.7 p[unit] for all three bars.

I am noticing I didn't really follow this specification, because my commits above made the sim look like this:
![image](https://cloud.githubusercontent.com/assets/154163/20018946/a549e96c-a28f-11e6-9037-3e664b0a6e77.png)

Did you want all three bars to have a matched numeric range (as if there's an imaginary x-axis for common reference)? In that case, the green bar would never stretch more than about 2/3 of the possible range. If this is not a problem, I'll change it to that.

**Comment by andrewadare** [comment]
To clarify my question, I think you might have been suggesting to make the constants [here](https://github.com/phetsims/capacitor-lab-basics/blob/14d6162058c23ff4d08845b307b08938ca7a0a7e/js/common/CLBConstants.js#L105-L113) all the same value (2.7e-12) instead of what they are now.

**Comment by arouinfar** [comment]
@andrewadare correct. The request was for all three bars to max out at 2.7E-12 in their respective units.

**Comment by andrewadare** [comment]
Got it, thanks for the clarification.
![image](https://cloud.githubusercontent.com/assets/154163/20019594/b9280308-a292-11e6-832e-41b6f9662289.png)
The three bars now have a common scale, set by the quantiy that takes on the largest possible value when the battery is connected.

**Comment by arouinfar** [comment]
Looks great @andrewadare!
