### ISSUE TITLE
Discretize plate area (add snap-to feature)

### ISSUE THREAD

**Issue by arouinfar** [phetsims/capacitor-lab-basics#153]
From Unfuddle
> Hi,
This is a minor problem but I'm using the Capacitor Lab for a physics class
https://phet.colorado.edu/en/simulation/capacitor-lab
and we are told to make the area of the plate "exactly" 250 mm^2.
The dragging handle does not allow for this, but is kind of jumpy.  I tried for many minutes and could only get it to 250.6.
I am using a Mac, and tried the accessibility features and using the cursor, as well as both a mouse and trackpad, and nothing was fine-grained enough.
I couldn't find a way to simply enter the value, which seems like ought to be a "mandatory" feature, especially for people who are disabled.
Anyhow, I love PhET and wanted to pass on my experience.

We discussed this briefly at the end of the 11/3/16 design meeting. It is difficult to precisely adjust the plate area, and it was suggested that @andrewadare add a snapping feature so that the plate area would be adjusted in steady increments. 10 mm^2 seems like a reasonable step size. The plate area would then increase like 100, 110, 120, 130...

We should also get rid of the decimal point if we add this feature.

**Comment by andrewadare** [comment]
I missed this issue at first and should have put https://github.com/phetsims/capacitor-lab-basics/issues/151#issuecomment-258470577 here. But part of that comment is moot because there is plenty of resolution to step in 10 mm^2 increments.

So this is completed and will be ready for review when I put up a new dev version.
