### ISSUE TITLE
Factor out MAX_PLATE_CHARGE_DISCONNECTED

### ISSUE THREAD

**Issue by samreid** [phetsims/capacitor-lab-basics#154]
In https://github.com/phetsims/phet-io/issues/801, we added this code:

```js
range: new Range( -MAX_PLATE_CHARGE_DISCONNECTED, MAX_PLATE_CHARGE_DISCONNECTED )
```

It would be better to compute this analytically instead of empirically.  @andrewadare can you look into this?

This is in a branch for now, but will be coming to master soon.

**Comment by andrewadare** [comment]
The changes made for #151 should help here (when the time comes), specifically the introduction of PLATE_CHARGE_METER_MAX_VALUE to CLBConstants.

**Comment by andrewadare** [comment]
@samreid I'm going to leave this assigned to you until you merge 1.3-phetio into master, then reassign to me (or feel free to reach out for collaboration when the time comes).

**Comment by samreid** [comment]
1.3-phetio is merged to master, please proceed at your convenience.

**Comment by andrewadare** [comment]
The global constant appears to be working for the slider in the instance proxies wrapper:

![image](https://cloud.githubusercontent.com/assets/154163/20023873/6e83a9cc-a2a8-11e6-9cf5-092c0d39eeb8.png)

Note that its numeric value is different than what you hard-coded because of the changes tracked in #151.

@samreid back over to you for review; close if this works for you as expected.

**Comment by samreid** [comment]
@phet-steele can you test this on phettest?

**Comment by phet-steele** [comment]
Works great for me, thanks @andrewadare.
