### ISSUE TITLE
Fill in credits

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/capacitor-lab-basics#168]
From the review checklist:

> Are the credits in sim-main.js correct?

For code review: https://github.com/phetsims/capacitor-lab-basics/issues/117

**Comment by andrewadare** [comment]
I took a shot, based on my own incomplete knowledge. @ariel-phet can you review this?
```
leadDesign: 'Amy Rouinfar',
softwareDevelopment: 'Andrew Adare, Jesse Greenberg, Chris Malley',
team: 'Ariel Paul, Kathy Perkins',
qualityAssurance: 'Steele Dalton, Amanda Davis, Bryce Griebenow, Elise Morgan, Oliver Orejola, Ben Roberts, Bryan Yoelin',
graphicArts: 'Amy Hanson, Amy Rouinfar',
```

**Comment by ariel-phet** [comment]
@arouinfar I think this is correct - do you want to have a gander?

**Comment by arouinfar** [comment]
The team should include Emily Moore and Emily Randall. It's also possible that Emily Randall ported some of the model, but @jessegreenberg would know for sure. QA seems reasonable, based on the sim's timeline. I think we can eliminate the graphic arts category. I don't believe @amyh-phet created any of the artwork (please correct me if I'm wrong!) and I wouldn't need to be credited there because I'm already credited as the lead.

**Comment by amyh-phet** [comment]
@arouinfar is correct.  I haven't worked on Capacitor lab, so I shouldn't be mentioned in the credits.

**Comment by andrewadare** [comment]
Thanks all, credits have been updated. Please reopen (or edit capacitor-lab-basics-main.js directly) if any further revisions are needed.
