### ISSUE TITLE
AbstractCircuit's createCircuitComponents

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/capacitor-lab-basics#171]
The following code feels a bit risky:
```js
    this.capacitors = this.circuitComponents.slice( 0, config.numberOfCapacitors );
    this.lightBulbs = this.circuitComponents.slice( config.numberOfCapacitors, config.numberOfLightBulbs + 1 );
```
Can AbstractCircuit either filter these (e.g. ```circuitComponents.filter( ... )```), or could it be passed a way to create capacitors/lightBulbs/others independently?

I don't see necessary documentation to tell what is included in the components, or how it relates to the counts, so it's hard for me to verify correctness at this point.

For code review: https://github.com/phetsims/capacitor-lab-basics/issues/117

**Comment by andrewadare** [comment]
As noted in the review comments, the job of createCircuitComponents should be done in the two subtypes of ParallelCircuit, namely CapacitanceCircuit and LightBulbCircuit. This function should just be removed from ParallelCircuit: it's too general, as it returns an arbitrary number of capacitors and light bulbs in an array. But there is only ever one capacitor, and zero or one light bulbs.

We should just have circuit.capacitor instead of circuit.capacitors, and circuit.lightBulb, which will be null for the first screen.

**Comment by andrewadare** [comment]
createCircuitComponents is gone, the arrays of circuitComponents, capacitors, and lightbulbs are all gone, and there's now just a circuit.capacitor and a circuit.lightBulb. The latter is defined to be null in CapacitanceCircuit, and there's only one place where the null check takes place in ParallelCircuit.

The circuit part of the model is looking much cleaner. There's more cleanup and refactoring left in ParallelCircuit, but that's covered by other issues.

**Comment by andrewadare** [comment]
This issue has been addressed, closing.
