### ISSUE TITLE
review open issues

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/capacitor-lab-basics#187]
@ariel-phet asked me to review open issues, to see what I might be able to address.

**Comment by pixelzoom** [comment]
@ariel-phet Should I skip the issues labeled "dev:ally"?   How about the ones labeled "priority:5-deferred"?

**Comment by ariel-phet** [comment]
@pixelzoom yes you can definitely skip "dev:a11y"

Maybe take a quick glance over "priority:5-deferred" - some of them are obviously not relevant for publication (like CAG, since we do not have that yet), but see if there is anything that you and I should discuss. My quick look suggests that deferred is correct for most of them.

**Comment by pixelzoom** [comment]
Summary of current open issues...

• 6 labeled `a11y` which can be safely ignored (#20, #21, #23, #24, #40)
• 2 labeled `deferred` for post 1.0.0 (#125, #176)
• 3 labeled `ready-for-review`, all they need is verification (#174, #180, #185)
• #184 not reproducible
• #175 needs to be done by @jonathanolson because it requires `kite` enhancements
• #117 code review is partially completed

Given the above... Having me take this over doesn't seem efficient or (to be honest) interesting.  It would take me quite a bit of time to become familiar enough with the issues to resolve them, even though most appear to be close to resolution.  And @jonathanolson could undoubtedly finish this sim relatively quickly if publishing it was a priority.

Assigning to @ariel-phet to decide how to proceed with completing this sim.

**Comment by ariel-phet** [comment]
Fair enough @pixelzoom, closing
