### ISSUE TITLE
Voltmeter reading values when a probe is on the battery

### ISSUE THREAD

**Issue by CWilson4960** [phetsims/capacitor-lab-basics#197]
Test device: MacBook Pro 

Operating System: OS Sierra 10.12.6

Browser: Chrome

Problem description: From the start, the voltmeter reading still reads a value when the negative probe is placed over the bottom of the battery up to a point on the battery. It stops reading and presents a question mark just below the -1.5 tick mark. This also occurs with the positive probe placed near the bottom of the battery. I found this on both a Chromebook in Chrome and on a MacBook in Chrome. 
Assigning @arouinfar 
@phet-steele thought it was most likely because the wire extends behind the battery to a certain extent, though we still thought it may be confusing to students.

Screenshots:
![capacitorlabbasics voltmeter](https://user-images.githubusercontent.com/31217926/32020961-249df354-b98f-11e7-9332-8c59ee3b15b5.jpeg)

phetsims/QA/issues/56
URL: https://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.5.0-dev.1/capacitor-lab-basics_en.html
Version: 1.5.0-dev.1 2017-10-18 16:42:15 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
Language: en-US
Window: 1235x625
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"8a8ff7d2","branch":"master"},"babel":{"sha":"0b5a4452","branch":"master"},"brand":{"sha":"cfca902d","branch":"master"},"capacitor-lab-basics":{"sha":"5fdf1748","branch":"master"},"chipper":{"sha":"b8a3c09a","branch":"master"},"dot":{"sha":"84bc5146","branch":"master"},"joist":{"sha":"e5c2e673","branch":"master"},"kite":{"sha":"067109a8","branch":"master"},"phet-core":{"sha":"054b2d6d","branch":"master"},"phetcommon":{"sha":"b13138d2","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"c9c3052a","branch":"master"},"scenery-phet":{"sha":"124c1c25","branch":"master"},"sherpa":{"sha":"0d590744","branch":"master"},"sun":{"sha":"082fee37","branch":"master"},"tandem":{"sha":"98e9917c","branch":"master"},"twixt":{"sha":"a2eaa10a","branch":"master"}}

**Comment by arouinfar** [comment]
Good catch @CWilson4960! I suspect @phet-steele is right -- the probe is likely reading over the hidden wire. This is a bit problematic, as users have no reason to know the probe is actually reading a wire.

@jonathanolson the voltmeter probes should not be able to read on top of the battery, other than the positive terminal (which is metallic).

**Comment by jonathanolson** [comment]
Moved the start of the wire down. It looks like it now behaves like other sections of wire. There's still a little bit of "offset" from the wire where it seems connected, but this seems to happen with everything else.

Does this look acceptable?

**Comment by arouinfar** [comment]
It's definitely an improvement @jonathanolson, but I think it could still use a bit more refinement (if feasible).

Probes are in the same location, but readings are different. The screenshot on the right exhibits the desired behavior, as the probe is touching a terminal.
![screen shot 2017-10-27 at 11 39 18 am](https://user-images.githubusercontent.com/8419308/32117408-7df09a10-bb0b-11e7-9f06-c71be070f3dc.png) ![image](https://user-images.githubusercontent.com/8419308/32117430-8d927a88-bb0b-11e7-8a14-274cc90660be.png)

Looks like it's still possible to get a voltage reading while the probe is on the battery casing, but it's an improvement over the latest dev.
![image](https://user-images.githubusercontent.com/8419308/32117494-d19580a4-bb0b-11e7-87fb-dcf770d763f3.png)

Perhaps drawing the battery in code will make it easier to distinguish between the battery terminal and casing?  If not, then I could live with the behavior as it is now.

**Comment by jonathanolson** [comment]
It seems there's a lot of "forgiveness" with precision with the current probes:
![clb-probe-1](https://user-images.githubusercontent.com/480878/32123128-51941a2c-bb20-11e7-8240-1802f1c8a3a3.PNG)

I assumed this was a feature?

Anyways, the entire boundary of the probe is tested (not just the tips):
![clb-probe-2](https://user-images.githubusercontent.com/480878/32123143-61cf731e-bb20-11e7-8158-c917d49347dc.PNG)

so in your current example where it is over the casing, it is also "effectively" over (or almost over) the end of the wire.

Did you want it so that if ANY part of the probe is near the battery casing, it will not register?

**Comment by jonathanolson** [comment]
Note that https://github.com/phetsims/capacitor-lab-basics/issues/197 may have slightly affected the position of the wire compared to the battery.

**Comment by arouinfar** [comment]
@jonathanolson, if any portion of the metallic part of the probes touches something conductive (wire, switch, battery terminals), the voltmeter should produce a non-? reading. The first screenshot is definitely problematic, but the 2nd one is acceptable because it looks like the base of the metal probes is touching the wire. 

@phet-steele commented that the bounds/test area of the metallic probe tips are likely to blame here. The bounds should be rotated rectangle encompassing only the metallic tip, but instead the probe tip runs diagonally through a square, so there's a lot of dead space near the probe. Can you clarify @phet-steele?

**Comment by jonathanolson** [comment]
I've fixed up the metallic probe tip shapes, and added a showDebugAreas query parameter to help with handling this.

Other things to note:

The light bulb base's shape is totally insufficient:
![screen shot 2017-10-31 at 9 02 18 pm](https://user-images.githubusercontent.com/480878/32258224-e1639798-be7e-11e7-8258-f325720176c8.png)

The battery terminal top is off (probably from recent changes), and will need fixing:
![screen shot 2017-10-31 at 9 03 18 pm](https://user-images.githubusercontent.com/480878/32258240-00eb763a-be7f-11e7-8bf7-cfc4ddc52a6e.png)

For some reason, the terminal top shape (a) doesn't seem to affect the probes at all, and (b) doesn't change when the battery flips. That will presumably need fixing (using the actual terminal shapes for hit testing).

The connection points (which look metallic) don't interact:
![screen shot 2017-10-31 at 9 05 52 pm](https://user-images.githubusercontent.com/480878/32258288-4f77d7ee-be7f-11e7-8123-e2603cecc890.png)

The wires don't test proper intersection, but instead whether the bounding box of the probe tip intersects (an x/y-axis aligned rectangle fully containing the probe tip). Results in weirdness:
![screen shot 2017-10-31 at 9 06 33 pm](https://user-images.githubusercontent.com/480878/32258315-7f4dd306-be7f-11e7-89c7-4457bc830ab0.png)

This is also the explanation for why the probe tips seem weird at the bottom of the battery:
![screen shot 2017-10-31 at 9 07 45 pm](https://user-images.githubusercontent.com/480878/32258346-a0f5770c-be7f-11e7-97c1-1431619ba26d.png)

The capacitor only checks the center of the probe tip, leading to weirdness:
![screen shot 2017-10-31 at 9 09 19 pm](https://user-images.githubusercontent.com/480878/32258376-cbddb1f0-be7f-11e7-8b1a-6251bab5eef5.png)

In addition, the battery terminal and light bulb base (broken for other reasons) also only test the bounding box of the probe.

@arouinfar, I presume all of these cases should be fixed? There may be performance impacts to properly checking for intersections (since the bounding-box and center intersections are way faster to compute). If things don't have to be perfectly precise (which is possible, but probably slightly slow), I can come up with approximations that perform well, so I'd like to know ahead-of-time what level of precision is acceptable.

**Comment by phet-steele** [comment]
> Can you clarify @phet-steele?

@jonathanolson very clearly demonstrated it in the latter part of the above comment (talking about the bounding box of the probe tip). Thanks JO!

**Comment by arouinfar** [comment]
> @arouinfar, I presume all of these cases should be fixed? 

Yes, I think all of these issues should be addressed @jonathanolson. Thanks for adding the showDebugAreas query parameter! It was very helpful. iPad performance is quite good, so I think we can afford to err towards accuracy.

You may want to review the CCK voltmeter or consult with @samreid about the probe tips. I believe he added a few extra sampling points to the metallic tip to check for intersections.

**Comment by jonathanolson** [comment]
One other thing that feels a bit weird is that the probe-able region of the switch segment doesn't change while the user is dragging the switch. For example, if you have the following setup:
![screen shot 2017-11-02 at 10 24 27 am](https://user-images.githubusercontent.com/480878/32337602-0f74fb24-bfb8-11e7-96ca-816b638f3ed1.png)

And drag the switch to the vertical position (without releasing), the voltmeter won't update:
![screen shot 2017-11-02 at 10 27 32 am](https://user-images.githubusercontent.com/480878/32337820-a56c797c-bfb8-11e7-80a8-42f5320c702a.png)

@arouinfar, presumably when the switch is dragged, the probe-able area of the wire should update as well?

**Comment by jonathanolson** [comment]
Applying work-in-progress in a branch, since there are a few kite fixes I'll need to apply (would error with fuzzing).

**Comment by arouinfar** [comment]
> @arouinfar, presumably when the switch is dragged, the probe-able area of the wire should update as well?

Ideally, yes @jonathanolson. If this is something you can address, please do. Nice catch!

**Comment by jonathanolson** [comment]
New probe areas for the light bulb base:
![screen shot 2017-11-02 at 12 23 40 pm](https://user-images.githubusercontent.com/480878/32343329-bd851766-bfc8-11e7-8773-6f3385837fbf.png)

**Comment by jonathanolson** [comment]
Added proper battery terminal handling (using the same shapes):

![screen shot 2017-11-02 at 1 19 58 pm](https://user-images.githubusercontent.com/480878/32345717-a897c88c-bfd0-11e7-8545-e6de2da9ae92.png)
![screen shot 2017-11-02 at 1 19 54 pm](https://user-images.githubusercontent.com/480878/32345718-a8b6522a-bfd0-11e7-994f-b9e56d0f383a.png)

**Comment by jonathanolson** [comment]
Merged to master. @arouinfar and @phet-steele, can you check the probe behavior to see if it looks good now?

?showDebugAreas may be helpful to visualize the locations.

**Comment by arouinfar** [comment]
Love it @jonathanolson!

**Comment by phet-steele** [comment]
> There may be performance impacts to properly checking for intersections (since the bounding-box and center intersections are way faster to compute)

iPad 2 performance is still usable.
