### ISSUE TITLE
Panel pixel polishing

### ISSUE THREAD

**Issue by arouinfar** [phetsims/capacitor-lab-basics#201]
@jonathanolson I've noticed a few things that could be tweaked slightly.

- [x] Remove "View" title from the panel. 
- [x] Top-align Bar Graph panel with View panel.
- [x] Reduce the size of checkboxes to roughly size of capital letter (like Pendulum Lab).
- [x] Anchor the View panel and toolbox so that they do not shift when switching screens.

For https://github.com/phetsims/QA/issues/56.

**Comment by jonathanolson** [comment]
Implemented, can you verify?

**Comment by arouinfar** [comment]
Everything's looking great @jonathanolson! 

One more nit-picky request, though. It looks like the Bar Graphs panel on the Light Bulb screen has some uneven padding. 
![image](https://user-images.githubusercontent.com/8419308/32388882-bef8081c-c08e-11e7-9ae2-92ae401043e5.png)
![image](https://user-images.githubusercontent.com/8419308/32388860-9e505ace-c08e-11e7-8715-5b286e60ff6d.png)

There appears to be less space above "Capacitance" and more space below "Stored Energy". The bars themselves appear to be equally distributed, so perhaps the checkbox + label is misaligned?

**Comment by jonathanolson** [comment]
You are correct, there is a 2-unit difference between the center of the labels and the center of the bars. Investigating.

**Comment by arouinfar** [comment]
> there is a 2-unit difference 

I suppose that's why we call it pixel polishing! 😄

**Comment by jonathanolson** [comment]
Weird, the fix was removing a deliberately-added offset of 2 in the code. Not sure why it was there.

@arouinfar can you test to see if it looks good, and if there's anything else?

**Comment by arouinfar** [comment]
Looks great @jonathanolson! I don't have any further requests.

**Comment by phet-steele** [comment]
> Weird, the fix was removing a deliberately-added offset of 2 in the code. Not sure why it was there.

Asked @jessegreenberg why it was there (he wrote it originally). It was done so that the value text for each bar ('0.00 pC" etc) would be aligned with the checkbox text ("Top Plate Charge" etc). If you look closely now at 1.5.0-dev.2, the value text is slightly above the text for its respective label.

**Comment by phet-steele** [comment]
1.5.0-dev.1
<img width="443" alt="screen shot 2017-11-03 at 3 36 18 pm" src="https://user-images.githubusercontent.com/5863899/32396957-1c63d0b2-c0ad-11e7-8f66-0aa6942c8f18.png">

1.5.0-dev.2
<img width="425" alt="screen shot 2017-11-03 at 3 36 03 pm" src="https://user-images.githubusercontent.com/5863899/32396956-1c4eb25e-c0ad-11e7-9251-9d885189f300.png">

1.5.0-dev.2 is more correct since baselines are aligned, BUT it looks so much worse (due to the font size differences)?

**Comment by arouinfar** [comment]
Looks like the real issue stems from differences in font size. Let's give the graph title and value the same font size @jonathanolson.

**Comment by phet-steele** [comment]
@arouinfar here is same font size:

<img width="922" alt="screen shot 2017-11-03 at 4 01 24 pm" src="https://user-images.githubusercontent.com/5863899/32397630-4dcdaa8a-c0b0-11e7-830a-98315c0d7616.png">

**Comment by phet-steele** [comment]
@jonathanolson please review.

@arouinfar is okay with the new look.

**Comment by jonathanolson** [comment]
Looks fine.
