### ISSUE TITLE
Issues with plate area and separation drag handles

### ISSUE THREAD

**Issue by samreid** [phetsims/capacitor-lab-basics#222]
While working on #218, I noticed that the grab handles look like this on startup:

![image](https://user-images.githubusercontent.com/679486/34735796-e5dd8de8-f52d-11e7-9075-0186b6560e96.png)

Dragging the vertical arrow up, or dragging the other arrow to the left have no effect, which was confusing to me.

Some possible resolutions include (a) starting the sliders in the middle of the range so motion in either direction will do something or (b) graying out one side of the arrow when it is at an extremum.

I know I'm just N=1 and that interviews may have already shown this to not be a problem, but I thought I'd bring it up to the design team in case you have considered this or in case you have observed problems like this in interviews.  I'm not sure who is on the design team so I'll assign to @ariel-phet to discuss or reassign.

**Comment by ariel-phet** [comment]
@arouinfar, thoughts here? The defaults start at nice round numbers (which seems good). Any insight from interviews?

**Comment by arouinfar** [comment]
Thanks for your comments @samreid! You raise a really good point. The default values match Java, and were likely chosen because 10 and 100 are nice, round numbers. While I didn't observe any issues with the default values in the interviews, I think starting somewhere in the middle would be better UX.

My initial thought was to start the plates at 5mm separation with an area of 200 mm^2, but I think the space between the plates looks a bit odd.
![image](https://user-images.githubusercontent.com/8419308/34741412-d6c919f0-f53f-11e7-8890-f299245a4eff.png)

Increasing the separation to 6 mm clearly shows two separate plates, which I think is nice on startup.
![image](https://user-images.githubusercontent.com/8419308/34741468-fdc8c7da-f53f-11e7-841d-8002bfb4b51c.png)

One could argue that 6 and 200 aren't the prettiest of numbers, but due to the factor of ε0 in the equation, the capacitance ends up nice and round at 0.30 pF. Additionally 6 mm is roughly in the middle of the 2-10 mm range, and a plate area of 200 mm^2 is double the minimum and half of the maximum, which makes for nice comparisons.

How does that sound @ariel-phet @samreid?

**Comment by arouinfar** [comment]
Looks like I forgot to reply to this suggestion
> (b) graying out one side of the arrow when it is at an extremum.

Excellent suggestion @samreid. I think graying out the arrow at its min/max would be a helpful visual cue, and consistent with how we handle min/max elsewhere in PhET sims.

**Comment by samreid** [comment]
Your comments seem reasonable to me, but it will ultimately be @ariel-phet's call.

**Comment by ariel-phet** [comment]
@samreid @arouinfar I think a default condition where suggested above (midway) seems good to me.

I actually don't think I would go the route of greying out the arrow. In this case the arrows are really drag handles, and I think the fact that you have hit a limit is fairly obvious from the sim, and a further visual cue is not necessary in my opinion. Especially with the new starting condition, you have two handles that basically say "you can expand/contract the plates, or you can make the separation larger or smaller" and either of those actions will now be possible at the beginning.

I feel like the downside of adding a half-grey arrow at the min/max would causing the potential "why is that grey?" question, which is unnecessary and a bit distracting. The handle as a whole is still usable, it has just met its limit.

**Comment by samreid** [comment]
I changed the capacitor separation and plate width accordingly, @jonathanolson can you please code review?

**Comment by jonathanolson** [comment]
Code changes look good to me.

**Comment by samreid** [comment]
Thanks @jonathanolson.  I posted a dev version here for review https://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.6.0-dev.2/phet/capacitor-lab-basics_en_phet.html

@arouinfar can you please take a look?

**Comment by arouinfar** [comment]
@samreid looks good to me!

For the record, I think @ariel-phet made some strong arguments against graying out the arrow, and I agree that the drag handler is a bit different.

**Comment by samreid** [comment]
Thanks, I think this issue can be closed (please reopen if I misconstrued something).

**Comment by arouinfar** [comment]
Reopening with `status:fixed-awaiting-deploy` for #237.

**Comment by samreid** [comment]
Reassigned to responsible-dev @jonathanolson (let me know if this is incorrect).

**Comment by arouinfar** [comment]
Sorry about that @samreid. I wasn't paying attention to the assignee when reopening.

**Comment by arouinfar** [comment]
Not sure when it happened, but this behavior is present in latest. Closing.
