### ISSUE TITLE
[1.6.7-rc.1/phetio] Wrappers do not work

### ISSUE THREAD

**Issue by JRomero0613** [phetsims/capacitor-lab-basics#238]
Test device: PC Laptop

OS: Windows 10 OS v. 1803

Browser: Google Chrome v. 67.0.3396.79

Problem description: For https://github.com/phetsims/QA/issues/128 when attempting to use various wrappers with CLB v. 1.6.7-phetio (found in https://github.com/phetsims/phet-io/issues/1329#issue-329557833) certain wrappers do not work even when using the &relativeSimPath and &launchLocalVersion query parameters. The wrappers that are not able to be accessed are the standalone, events: colorized, events: JSON, and events: recording. Due to the fact that events: recording does not work the events: playback wrapper is also unable to be tested. Is there another query parameter that could be used to access these wrappers or is there an issue with this newest version? I have tested all of these wrappers the previous version, 1.6.6, and they all work as expected.

**Comment by lmulhall-phet** [comment]
Events: recording works. Need to add the `&console` query parameter as well as `&relativeSimPath`.

**Comment by lmulhall-phet** [comment]
I'm not seeing the above issue in master.

**Comment by zepumph** [comment]
It looks like this version of the index wrapper is filling in links with the phet-io website. Not sure why, but I see that the standalone and instance proxies links work, have you tested those alright? Here is what I'm seeing from the original task. 

1.6 (RC, chipper 2.0 BUT not a shared branch with phet brand)
  [Standalone](https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.6.7-rc.1/phet-io/capacitor-lab-basics_all_phet-io.html?phetioStandalone)
  [Instance Proxies](https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.6.7-rc.1/phet-io/wrappers/instance-proxies/instance-proxies.html?link&relativeSimPath)

Then please test the following links (manually created rather than using the faulty index wrapper).
[State](https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.6.7-rc.1/phet-io/wrappers/state/state.html?relativeSimPath)
[Mirror Inputs](https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.6.7-rc.1/phet-io/wrappers/mirror-inputs/mirror-inputs.html?relativeSimPath)

**Comment by JRomero0613** [comment]
@zepumph I have tested all of the links you provided in your last comment and they all work. I have also tested the wrappers that did not work (standalone, events: colorized, events: JSON, and events: recording) in master and they all work as well. If you have links for those wrappers I can them test for you.

**Comment by zepumph** [comment]
I'm not sure all of these are necessary, but here you go.

- [ ] active: https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.6.7-rc.1/phet-io/wrappers/active/active.html?relativeSimPath
- [ ] screenshot: https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.6.7-rc.1/phet-io/wrappers/screenshot/screenshot.html?relativeSimPath
- [ ] recording: https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.6.7-rc.1/phet-io/wrappers/record/record.html?relativeSimPath&console
- [ ] Events text: https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.6.7-rc.1/phet-io/wrappers/event-log/event-log.html?relativeSimPath
- [ ] console log: https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.6.7-rc.1/phet-io/capacitor-lab-basics_all_phet-io.html?phetioStandalone&phetioLog=lines

**Comment by JRomero0613** [comment]
@zepumph I just tested all of the links you gave me and they all work. It must be an issue with the index wrapper as you suggested earlier.

**Comment by zepumph** [comment]
We will not be fixing this on the branch, and it is fixed in master, closing
