### ISSUE TITLE
Question: Any way to increase font-size/scaling of the PHET Sim inside an iframe?

### ISSUE THREAD

**Issue by firasm** [phetsims/capacitor-lab-basics#273]
hello! first of all, thanks so much for all of the excellent PHET sims! I really enjoy teaching with them.

I am trying a new teaching technology (Jupyter Notebooks) when teaching a lecture and I have two questions:

1. I'm struggling with how to increase the font/text/element size while the phet SIM is embedded inside an iframe. 
<img width="1497" alt="Screen Shot 2020-06-19 at 11 11 11 PM" src="https://user-images.githubusercontent.com/2507459/85190109-04d8d300-b283-11ea-8942-91fe05224b48.png">

The text (circled in purple) is most I'm interested in increasing the size. Is there a setting (perhaps an iframe property or CSS) that will allow me to change the size?

2. Relatedly, there is a lot of empty space in the sim and it would be useful to make the sim "responsive" ?

Thanks in advance!

**Comment by ariel-phet** [comment]
@firasm unfortunately with the sim "as is" from our website if you are embedding it, there are not easy ways to change those sizes. Since our sims are designed to handle translated strings and such we have built in max widths and such for strings and have not explored the functionality you are requesting. As for all the empty space, if you choose the size of the embedding window to better match the aspect ratio of the sim, you can at least remove the empty space on the top and bottom.

Our code is of course all open source, so if you are skilled with Javascript you could consider making a local copy of the sim and adjusting these font size and such as you see fit.

**Comment by firasm** [comment]
sounds good - thanks for the reply! 

Next time I'll have a chance to do this is likely the summer so we can close the issue for now, or leave it open - as you wish!

**Comment by Denz1994** [comment]
Closing this issue for now. If any further work is expected to be done here, we can reopen when that time comes.
