### ISSUE TITLE
Use only one decimal place in StopwatchNode display

### ISSUE THREAD

**Issue by arouinfar** [phetsims/capacitor-lab-basics#274]
In https://github.com/phetsims/scenery-phet/issues/565 StopwatchNode gained the option of having only 1 decimal place in the readout. Since the StepForwardButton increment is 0.2s, the StopwatchNode doesn't need more than 1 decimal place.

@Denz1994 please update the StopwatchNode display to have only one decimal place.

**Comment by arouinfar** [comment]
See https://github.com/phetsims/scenery-phet/issues/617 for further discussion of StopwatchNode precision.

**Comment by samreid** [comment]
StopwatchNode number of decimal places options are discussed in https://github.com/phetsims/scenery-phet/issues/618

**Comment by Denz1994** [comment]
After changes in https://github.com/phetsims/scenery-phet/issues/618 it was fairly easy to use only one decimal place.

As a side note here are some changes I would make to  the implementation of StopWatch in CLB:

- [ ] `timer` in `VoltmeterToolboxPanel.js` should be refactored to reflect that it is just used as a placeholder. Maybe `psuedoStopWatch` or `StopWatchImage`. 
- [ ] CapacitanceScreenView.js doesn't need a stopwatch at all because it isn't on that screen.
- [ ] `VoltmeterToolboxPanel.js` should be a `ToolboxPanel.js` because it doesn't just include the voltmeter anymore.

**Comment by jonathanolson** [comment]
Completed.
