### ISSUE TITLE
Light possibly too bright?

### ISSUE THREAD

**Issue by brooklynlash** [phetsims/capacitor-lab-basics#275]
This is just a suggestion for https://github.com/phetsims/QA/issues/565, but I think the light when switching from the voltage to the light source is too bright. 
![capacitor1](https://user-images.githubusercontent.com/72031637/96283592-ae15a880-0f99-11eb-8062-7561f79e4d1d.gif)

**Comment by Denz1994** [comment]
Reducing the brightness would mean reducing the scale of each white circle radius. I'd leave for @arouinfar to determine the appropriate ratio, assuming we want to change this scale.

**Comment by arouinfar** [comment]
Thanks @brooklynlash. I agree.

@Denz1994 let's turn down the max brightness. I played around with the code locally, and I think changing https://github.com/phetsims/capacitor-lab-basics/blob/master/js/common/view/BulbNode.js#L56 to the following works nicely.

```js
  const bulbBrightnessMap = new LinearFunction( 0, 5E-13, 0, 175, true );
```

**Comment by Denz1994** [comment]
The adjustment was made on the 1.7 branch. I'll push a new version for comparison.

**Comment by KatieWoe** [comment]
This seems to have been implemented in rc.8. Due to https://github.com/phetsims/capacitor-lab-basics/issues/276 I'm leaving open in case further adjustments relating to this are needed.

**Comment by KatieWoe** [comment]
Addition: in rc.8 I noticed that, when making changes beyond the max brightness of the bulb, the fact that the light stops changing can be a bit odd and may lead to some misunderstandings.
![maxlightlooksodd](https://user-images.githubusercontent.com/41024075/104650390-5b6c8b00-5673-11eb-893c-1867eb5286b8.gif)

**Comment by arouinfar** [comment]
I don't think it pedagogically useful to change the capacitance while discharging, which is why I decided to keep the arrows layered behind the halo in #276. However, I do think we could afford to increase the max brightness a bit to reduce the likelihood of running into a situation like the one in https://github.com/phetsims/capacitor-lab-basics/issues/275#issuecomment-760483503. Since we'll be moving the TimeControlNode on top of the halo, we can afford to make the halo a bit larger. @Denz1994 let's increase the max brightness to 225.

**Comment by jonathanolson** [comment]
Master and 1.7 had diverged, so I have NOT pushed this to 1.7.

Can you see the behavior in master and let me know if it looks good? And then explicitly let me know if I should move it to 1.7?

**Comment by arouinfar** [comment]
Looks good in master. Since we'll be taking new SHAs, I think we can close.
