### ISSUE TITLE
Should arrows change if the type is changed while another is present

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/capacitor-lab-basics#281]
For https://github.com/phetsims/QA/issues/588.
This is a suggestion and not much of an issue, so feel free to close if this isn't needed. When charges move and current direction arrows are on, the blue or red arrow will appear for a time and then disappear. If you switch options (from electrons to conventional or vice versa) while that arrow is visible, nothing changes. Should the arrow change in this case? Seen more easily if speed is set to slow or paused.
![shouldarrowchange](https://user-images.githubusercontent.com/41024075/104661796-8e6c4a00-5686-11eb-86c0-62ed42d44b69.gif)

**Comment by arouinfar** [comment]
Good find, @KatieWoe. This actually looks like a bug to me because the current arrow becomes out of sync with the selected radio button. @Denz1994 is it possible to switch arrow type midway? If not, we could immediately hide the current arrow rather than continuing to display the wrong arrow type until it fades away.

**Comment by jonathanolson** [comment]
There was a LOT of weird handling here... I changed a lot of this code, and I believe this should now work nicely in master. @KatieWoe can you verify?

**Comment by KatieWoe** [comment]
This part looks ok on master.

**Comment by KatieWoe** [comment]
Looks ok in dev.5. Closing
