### ISSUE TITLE
When connected to light bulb, the plate charge increases as capacitance increases

### ISSUE THREAD

**Issue by arouinfar** [phetsims/capacitor-lab-basics#56]
Tested on latest Mac/Chrome and Mac/Safari as part of https://github.com/phetsims/tasks/issues/575. 

The charge on the plates will increase if the capacitance is increased (by increasing area or decreasing separation of the plates) while the capacitor is being discharged through the bulb.

To reproduce, charge the capacitor, switch to light bulb, increase plate area while discharging. In the example below, the plate charge dissipates from 0.13 pC to 0.01 pC. Once the plate area is increased, the plate charge jumps to 0.23 pC, which means the sim has somehow managed to create charge. 

![clb_increasedcharge](https://cloud.githubusercontent.com/assets/8419308/14551446/7ab2caec-0290-11e6-9a1f-83ac1a865908.gif)

**Comment by jessegreenberg** [comment]
Thanks for catching this @arouinfar.  This used to happen whenever the capacitor changed geometry, regardless of its connection to the battery.  Looks like this was somehow missed when the other cases were fixed.

**Comment by jessegreenberg** [comment]
Fixed a case issue in the commit above, but this is not resolved yet.  My capacitor physics is a bit rusty, and I am not sure how this *should* behave. The capacitor discharges according to 

Vc = Vo*exp( -t / ( R * C ) )

where t is the time and R*C is the time constant.  Now C is increasing, which is why we are seeing the increase in voltage and charge.  Perhaps Vo needs to update somehow to compensate for changing capacitance? @arouinfar would you mind describing how the capacitor should behave?

**Comment by jessegreenberg** [comment]
Quick plot of the model as it is now with variable time and capacitance:

![capture](https://cloud.githubusercontent.com/assets/6396244/14572904/c93e4c1c-030e-11e6-9676-573360664e66.PNG)

**Comment by arouinfar** [comment]
@jessegreenberg, if a charged capacitor is not connected to anything else, the amount of charge on its plates must remain a constant.  The voltage across the capacitor is inversely proportional to the capacitance. C = Q/V

Suppose the capacitor has capacitance C1 with charge Q1 and voltage V1. The capacitance is instantaneously increased to C2. (An instantaneous increase allows us to ignore the charge lost from draining while the capacitance is being changed.) The charge will still remain Q1, but the voltage will decrease proportionally form V1 to V2. So if C2 = 2*C1, V2 = V1/2.

Because the capacitance has changed, the RC time constant has also changed (meaning the rate of drainage has changed).  

In the equation Vc = Vo*exp( -t / ( R * C ) )
V0 should now become V2 and C should become C2.

The only tricky part is what happens when the time it takes to change the capacitance is non-zero. It seems like there could potentially be performance issues if you pick very small time steps and constantly recalculate a new V0 and C.

**Comment by jessegreenberg** [comment]
@arouinfar thanks for the very detailed explanation!  That makes total sense.  I have worked this into the model and I think it is behaving correctly, charge is conserved once again.  I don't expect that these changes will be too performance intensive but we will double check.  We will have a dev version published shortly so that you can review the behavior.

**Comment by arouinfar** [comment]
That's great @jessegreenberg! Thanks

**Comment by jessegreenberg** [comment]
Here is a dev version with this change, @arouinfar would you mind reviewing to make sure this is the correct behavior?

http://www.colorado.edu/physics/phet/dev/html/capacitor-lab-basics/1.0.0-dev.17/capacitor-lab-basics_en.html

**Comment by arouinfar** [comment]
Looks good @jessegreenberg! Closing.
