### ISSUE TITLE
Match tandem names

### ISSUE THREAD

**Issue by samreid** [phetsims/capacitor-lab-basics#88]
During #79 I noticed this mapping between check box text and tandems:

Some have great matching names like so:
"Plate Charges" => plateChargesCheckBox => plateChargesVisibleProperty

Some have a mismatch:
"Bar Graphs" => barGraphsCheckBox => barGraphsPanelVisibleProperty

Generally it is OK if there is a slight difference between the text and var name such as "Bar Graphs" and "barGraphsVisible", but the CheckBox and Property prefixes should match.

There is also a mismatch between:
"Electric Field" => electricFieldCheckBox => eFieldVisibleProperty

and 
"Current" => currentCheckBox => currentIndicatorsVisibleProperty

Please address these issues and review the other simulation text to ensure the tandem prefixes match (and generally match any on-screen English text, though it is ok to add suffixes like Visible and VisibleProperty).

**Comment by samreid** [comment]
Likewise the `plateAreaDragHandleNode` changes the `plateSizeProperty`, perhaps we should use `plateArea` for both since `"Plate Area"` is what appears in the English text.

**Comment by andrewadare** [comment]
I think the remaining visibility properties including the word "Meter", e.g. in this block

https://github.com/phetsims/capacitor-lab-basics/blob/bb0c811f9226c7989f1cd96a935d662c5f2ba389/js/common/model/CLBModel.js#L33-L50

are best left as they are, because they are more descriptive that way, and they would look very similar to other named properties if it were omitted. More relevant for this issue, they don't seem to have the same consistency problem as the others (which are now fixed).

**Comment by andrewadare** [comment]
All the naming is consistent now, closing.
